#!/bin/sh

mkdir -p /var/run/spamd
chown spamd:root /var/run/spamd

sleep 60

find /tmp/ -name '.spamassassin*' -type d -delete

exec /usr/sbin/spamd --max-children 3 --username=spamd --nouser-config --socketpath=/var/run/spamd/spamd --socketmode=660 --socketowner=spamd --socketgroup=users

