#!/bin/bash
# $Header:  Exp $

# net-misc/rsync supervise script

[ -f /etc/conf.d/rsyncd ] && source /etc/conf.d/rsyncd

exec 2>&1
exec /usr/bin/rsync --daemon --no-detach ${RSYNC_OPTS} --config=/etc/rsync/rsyncd.conf


