#!/bin/sh

# net-mail/courier-imap supervise script
# imapd-ssl component

sleep 20

# logging will be done by multilog
exec 2>&1

[[ -f /etc/courier-imap/pop3d && -f /etc/courier-imap/pop3d-ssl ]] || {
	echo 'configuration files are missing'
	sleep 30
	exit 1
}

prefix=/usr
exec_prefix=/usr
bindir=/usr/sbin
libexecdir=/usr/lib/courier-imap

source /etc/courier-imap/pop3d
source /etc/courier-imap/pop3d-ssl

export POP3_TLS=1
export POP3_STARTTLS=NO
export POP3_TLS_REQUIRED=0

eval `sed -n '/^#/d;/=/p' </etc/courier-imap/pop3d | \
                sed 's/=.*//;s/^/export /;s/$/;/'`
eval `sed -n '/^#/d;/=/p' </etc/courier-imap/pop3d-ssl | \
                sed 's/=.*//;s/^/export /;s/$/;/'`

/usr/bin/tcpserver -v -c${MAXDAEMONS} -v -R -H ${SSLADDRESS} ${SSLPORT} \
${bindir}/couriertls -server -tcpd ${bindir}/pop3login \
${libexecdir}/courier-pop3d.indirect ${MAILDIRPATH} || sleep 10

